package com.ctzj.eai.dao.track.entity;

public class SRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_role.id
     *
     * @mbggenerated Fri Aug 12 10:56:17 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_role.name
     *
     * @mbggenerated Fri Aug 12 10:56:17 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_role.description
     *
     * @mbggenerated Fri Aug 12 10:56:17 CST 2016
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_role.id
     *
     * @return the value of s_role.id
     *
     * @mbggenerated Fri Aug 12 10:56:17 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_role.id
     *
     * @param id the value for s_role.id
     *
     * @mbggenerated Fri Aug 12 10:56:17 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_role.name
     *
     * @return the value of s_role.name
     *
     * @mbggenerated Fri Aug 12 10:56:17 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_role.name
     *
     * @param name the value for s_role.name
     *
     * @mbggenerated Fri Aug 12 10:56:17 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_role.description
     *
     * @return the value of s_role.description
     *
     * @mbggenerated Fri Aug 12 10:56:17 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_role.description
     *
     * @param description the value for s_role.description
     *
     * @mbggenerated Fri Aug 12 10:56:17 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }
}